#! /bin/sh

pkill sxhkd
sxhkd &

for disp in $(bspc query -M --names); do
    MONLIST=""
    echo $disp
    for num in $(seq 9); do
        MONLIST="$MONLIST $disp-$num"
    done
    bspc monitor -f $disp
    bspc monitor -d $MONLIST
    polybar $disp &
done

feh $HOME/Downloads/forest.jpg --bg-fill



bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
